development:
  adapter: postgresql
  encoding: unicode
  database: solute_development
  username: postgres
  password: postgres
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: solute_production
  username: postgres
  password: postgres
  pool: 5
